public type EventType "CURRENT"|"EXPIRED"|"ALL"|"RESET"|"TIMER";
public type JoinType "INNER"|"LEFT"|"RIGHT"|"FULL";
public string OUTPUT = "OUTPUT";
public string ASCENDING = "ascending";
public string DESCENDING = "descending";
public EventType RESET = "RESET";
public EventType EXPIRED = "EXPIRED";
public string DEFAULT = "DEFAULT";
public EventType CURRENT = "CURRENT";
public EventType TIMER = "TIMER";
public string DELIMITER = ".";
public string DELIMITER_REGEX = "\\.";